### PR TITLE
Unroll some inner loops

### PR DESCRIPTION
**Pull request by donovanhide**
These unrolled loops improve performance significantly. Can include a benchmark if needed?

### CODE REVIEW

**Comment by donovanhide** [comment]
`benchcmp` output for latest commits
```benchmark                  old ns/op     new ns/op     delta
BenchmarkKeyGeneration     132027        66607         -49.55%
BenchmarkSigning           132649        69645         -47.50%
BenchmarkVerification      267982        204192        -23.80%
```

**Comment by DavidVorick** [comment]
At the very least you don't need constant time operations in the verification code.

**Comment by agl** [comment]
This was very hard to review, but I believe that it's correct, thanks!

I dropped the change to cmove because constant-time requires that the trace of instructions and data fetches be equal.

(GitHub mightn't think that it has been merged because of the rebase to drop that change.)

**Comment by donovanhide** [comment]
Thanks for merging! 
Maybe one day the Go compiler SSA work might be able to do all the register and instruction order optimisation automatically, but I needed fast as possible signing for a project, so it seemed worth the effort.
> This was very hard to review
I feel like that with some of djb's code :-)

**Pull request closed without merging**
